// <auto-generated />
namespace Daftari.Chemicals.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitChemicals : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitChemicals));
        
        string IMigrationMetadata.Id
        {
            get { return "202106211628538_InitChemicals"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
