// <auto-generated />
namespace Daftari.Pike13Api.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Webhooks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Webhooks));
        
        string IMigrationMetadata.Id
        {
            get { return "202108211648222_Webhooks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
